name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Checkout MSVC repo
        uses: actions/checkout@v7
        with:
          repository: itsmattkc/msvc600
          path: msvc600

      - name: Build
        shell: cmd
        run: |
          call .\msvc600\VC98\Bin\VCVARS32.BAT
          cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "NMake Makefiles"
          cmake --build build
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: |
            build/spel.exe
            build/spel.pdb
    
  verify:
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          name: build
          path: build
      
      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          cache: 'pip' # caching pip dependencies

      - name: Install Reccmp
        run: |
          pip install -r requirements.txt
      
      - name: Detect Binaries
        run: |
          reccmp-project detect --what original   --search-path original
          dir
          dir build
          reccmp-project detect --what recompiled --search-path build
      
      - name: Summarize Accuracy
        run: |
          reccmp-reccmp --target SPEL -S progress.svg --json progress.json
      
      - name: Check Vtables
        shell: bash
        run: |
          reccmp-vtable --target SPEL

      - name: Check Variables
        shell: bash
        run: |
          reccmp-datacmp --target SPEL

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Accuracy Report
          path: |
            progress*



